# Generated by Django 2.2.1 on 2019-05-19 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190519_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['completed', 'priority', 'title']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 26, 18, 2, 17, 272888), null=True),
        ),
    ]
